services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    command:  ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: easyemail
    networks:
      - app-network 

  log-sign:
    build:
      context: ./services/log-sign
    container_name: log-sign
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - ./services/log-sign/.env
    networks:
      - app-network

  core:
    build:
      context: ./services/core
    container_name: core
    ports:
      - "5002:5001"
    depends_on:
      - mongo
    env_file:
      - ./services/core/.env
    networks:
      - app-network

  summarizer:
    build:
      context: ./services/summarizer
    container_name: summarizer
    ports:
      - "5003:5002"
    depends_on:
      - mongo
    env_file:
      - ./services/summarizer/.env
    networks:
      - app-network
  
  frontend:
    build:
      context: ./oe_test
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - log-sign
      - core
      - summarizer
    networks:
      - app-network


volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
