# Use official Node.js LTS image
FROM node:18

# Set working directory
WORKDIR /app

# Install only what's needed
COPY package*.json ./
# RUN npm ci --omit=dev
RUN npm i

# Copy app files
COPY . .

# Environment variables
# ENV NODE_ENV=production

# Command to run your worker
CMD ["node", "emailWorker.js"]
